version: '3.5'
services:
  blog:
    image: node:20-alpine3.19
    container_name: blog
    working_dir: /usr/src/blog
    ports:
      - 8080:8080
    command: npm run dev
    volumes:
      - ./:/usr/src/blog